// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/search/search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Comic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comic) Reset() {
	*x = Comic{}
	mi := &file_proto_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comic) ProtoMessage() {}

func (x *Comic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comic.ProtoReflect.Descriptor instead.
func (*Comic) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *Comic) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comic) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comics        []*Comic               `protobuf:"bytes,1,rep,name=comics,proto3" json:"comics,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetComics() []*Comic {
	if x != nil {
		return x.Comics
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ComicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComicRequest) Reset() {
	*x = ComicRequest{}
	mi := &file_proto_search_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComicRequest) ProtoMessage() {}

func (x *ComicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComicRequest.ProtoReflect.Descriptor instead.
func (*ComicRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{3}
}

func (x *ComicRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ComicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Titles        []string               `protobuf:"bytes,3,rep,name=titles,proto3" json:"titles,omitempty"`
	Alts          []string               `protobuf:"bytes,4,rep,name=alts,proto3" json:"alts,omitempty"`
	Transcripts   []string               `protobuf:"bytes,5,rep,name=transcripts,proto3" json:"transcripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComicInfo) Reset() {
	*x = ComicInfo{}
	mi := &file_proto_search_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComicInfo) ProtoMessage() {}

func (x *ComicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComicInfo.ProtoReflect.Descriptor instead.
func (*ComicInfo) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{4}
}

func (x *ComicInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ComicInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ComicInfo) GetTitles() []string {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *ComicInfo) GetAlts() []string {
	if x != nil {
		return x.Alts
	}
	return nil
}

func (x *ComicInfo) GetTranscripts() []string {
	if x != nil {
		return x.Transcripts
	}
	return nil
}

var File_proto_search_search_proto protoreflect.FileDescriptor

const file_proto_search_search_proto_rawDesc = "" +
	"\n" +
	"\x19proto/search/search.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\";\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\")\n" +
	"\x05Comic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"I\n" +
	"\x0eSearchResponse\x12!\n" +
	"\x06comics\x18\x01 \x03(\v2\t.pb.ComicR\x06comics\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x1e\n" +
	"\fComicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"{\n" +
	"\tComicInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06titles\x18\x03 \x03(\tR\x06titles\x12\x12\n" +
	"\x04alts\x18\x04 \x03(\tR\x04alts\x12 \n" +
	"\vtranscripts\x18\x05 \x03(\tR\vtranscripts2\x8f\x02\n" +
	"\rSearchService\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12/\n" +
	"\x06Search\x12\x11.pb.SearchRequest\x1a\x12.pb.SearchResponse\x120\n" +
	"\aISearch\x12\x11.pb.SearchRequest\x1a\x12.pb.SearchResponse\x126\n" +
	"\x04Drop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12+\n" +
	"\bGetComic\x12\x10.pb.ComicRequest\x1a\r.pb.ComicInfoB\x1fZ\x1dyadro.com/course/proto/searchb\x06proto3"

var (
	file_proto_search_search_proto_rawDescOnce sync.Once
	file_proto_search_search_proto_rawDescData []byte
)

func file_proto_search_search_proto_rawDescGZIP() []byte {
	file_proto_search_search_proto_rawDescOnce.Do(func() {
		file_proto_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_search_proto_rawDesc), len(file_proto_search_search_proto_rawDesc)))
	})
	return file_proto_search_search_proto_rawDescData
}

var file_proto_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_search_search_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: pb.SearchRequest
	(*Comic)(nil),          // 1: pb.Comic
	(*SearchResponse)(nil), // 2: pb.SearchResponse
	(*ComicRequest)(nil),   // 3: pb.ComicRequest
	(*ComicInfo)(nil),      // 4: pb.ComicInfo
	(*emptypb.Empty)(nil),  // 5: google.protobuf.Empty
}
var file_proto_search_search_proto_depIdxs = []int32{
	1, // 0: pb.SearchResponse.comics:type_name -> pb.Comic
	5, // 1: pb.SearchService.Ping:input_type -> google.protobuf.Empty
	0, // 2: pb.SearchService.Search:input_type -> pb.SearchRequest
	0, // 3: pb.SearchService.ISearch:input_type -> pb.SearchRequest
	5, // 4: pb.SearchService.Drop:input_type -> google.protobuf.Empty
	3, // 5: pb.SearchService.GetComic:input_type -> pb.ComicRequest
	5, // 6: pb.SearchService.Ping:output_type -> google.protobuf.Empty
	2, // 7: pb.SearchService.Search:output_type -> pb.SearchResponse
	2, // 8: pb.SearchService.ISearch:output_type -> pb.SearchResponse
	5, // 9: pb.SearchService.Drop:output_type -> google.protobuf.Empty
	4, // 10: pb.SearchService.GetComic:output_type -> pb.ComicInfo
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_search_search_proto_init() }
func file_proto_search_search_proto_init() {
	if File_proto_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_search_proto_rawDesc), len(file_proto_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_search_proto_goTypes,
		DependencyIndexes: file_proto_search_search_proto_depIdxs,
		MessageInfos:      file_proto_search_search_proto_msgTypes,
	}.Build()
	File_proto_search_search_proto = out.File
	file_proto_search_search_proto_goTypes = nil
	file_proto_search_search_proto_depIdxs = nil
}
