FROM golang:1.25 AS build

RUN apt-get update && apt-get install -y protobuf-compiler && \
  rm -rf /var/lib/apt/lists/*

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

ENV GOEXPERIMENT=greenteagc
ENV PATH="$PATH:$(go env GOPATH)/bin"
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY pkg ./pkg
COPY api ./api

RUN protoc --go_out=.      --go_opt=paths=source_relative \
  --go-grpc_out=. --go-grpc_opt=paths=source_relative \
  proto/words/words.proto


ENV CGO_ENABLED=0
RUN go build -o /api api/main.go

FROM alpine:3.20

COPY --from=build /api /api

ENTRYPOINT [ "/api" ]
