FROM golang:1.25 AS build

RUN apt-get update && apt-get install -y protobuf-compiler && \
  rm -rf /var/lib/apt/lists/*

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

ENV PATH="$PATH:$(go env GOPATH)/bin"
ENV GOEXPERIMENT=greenteagc
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY pkg ./pkg
COPY search ./search

RUN protoc --go_out=.      --go_opt=paths=source_relative \
  --go-grpc_out=. --go-grpc_opt=paths=source_relative \
  proto/search/search.proto


ENV CGO_ENABLED=0
RUN go build -o /search search/main.go

# distroless better =)
FROM alpine:3.20

COPY --from=build /search /search

ENTRYPOINT [ "/search" ]

