FROM golang:1.25 AS build

ENV GOEXPERIMENT=greenteagc
ENV CGO_ENABLED=0

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY pkg ./pkg
COPY frontend ./frontend

RUN go build -o /frontend ./frontend/main.go

FROM alpine:3.20
COPY --from=build /frontend /frontend
ENTRYPOINT ["/frontend"]
